export interface NotificationConfig {
    id: string;
    title?: string;
    eventType?: string;
    active: boolean;
    channel: ('SMS' | 'Email')[];
    subject: string;
    trigger: string;
    recipients: string[];
    template?: string;
    lastEdited?: string;
}

export const MOCK_CORE_NOTIFICATIONS: NotificationConfig[] = [

    {
        id: "EC-001",
        title: "Submission Received",
        subject: "Grievance {{id}} Received — OAN Ethiopia",
        recipients: ["Submitter"],
        channel: ["SMS", "Email"],
        trigger: "Immediately on save",
        active: true,
        template: "Dear {{name}},\n\nYour grievance has been successfully registered on the OAN Ethiopia Portal.\n\nTicket Number: {{id}}\nService Category: {{category}}\nGrievance Type: {{grievanceType}}\nAssigned Department: {{dept}}\nSLA Window: {{slaDays}} working days\n\nYou will be notified of all updates via SMS and email.\n\nOAN Ethiopia Grievance Portal",
        lastEdited: "2026-04-01T09:00:00Z",
    },
    {
        id: "EC-002",
        title: "Duplicate Detected",
        subject: "Possible Duplicate Submission — Grievance {{id}}",
        recipients: ["Submitter"],
        channel: ["SMS", "Email"],
        trigger: "On validation",
        active: true,
        template: "Dear {{name}},\n\nA similar grievance ({{existingId}}) was recently submitted by your account.\n\nIf this is a new issue, please proceed with justification. Otherwise, you may track your existing grievance using the ticket number above.\n\nOAN Ethiopia Grievance Portal",
        lastEdited: "2026-04-01T09:00:00Z",
    },
    {
        id: "EC-003",
        eventType: "Grievance Assigned (Auto-routing)",
        subject: "[OAN] Grievance {{id}} Assigned — Action Required",
        recipients: ["L1 Officer"],
        channel: ["Email"],
        trigger: "On auto-routing match",
        active: true,
        template: "Dear {{officerName}},\n\nGrievance {{id}} has been automatically assigned to your department.\n\nSubmitter: {{submitterName}} ({{submitterType}})\nCategory: {{category}} — {{grievanceType}}\nPriority: {{priority}}\nLocation: {{region}}, {{woreda}}, {{kebele}}\nSLA Deadline: {{slaDeadline}}\n\nPlease log in to the OAN Portal to review and action this grievance.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-05T10:30:00Z",
    },
    {
        id: "EC-004",
        title: "Grievance Assigned (Manual Routing)",
        subject: "[OAN] Grievance {{id}} Manually Assigned",
        recipients: ["L1 Officer"],
        channel: ["Email"],
        trigger: "On nodal officer assignment",
        active: true,
        template: "Dear {{officerName}},\n\nGrievance {{id}} has been manually assigned to your department by the Nodal Officer.\n\nSubmitter: {{submitterName}}\nCategory: {{category}} — {{grievanceType}}\nSLA Deadline: {{slaDeadline}}\n\nPlease action promptly.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-05T10:30:00Z",
    },
    {
        id: "EC-005",
        title: "Status → In Progress",
        subject: "Your Grievance {{id}} Is Being Processed",
        recipients: ["Submitter"],
        channel: ["SMS"],
        trigger: "Officer accepts ticket",
        active: true,
        template: "OAN: Grievance {{id}} is now In Progress. Department: {{dept}}. Officer: {{officerName}}. We will update you shortly. Reply STOP to opt out.",
        lastEdited: "2026-04-10T14:00:00Z",
    },
    {
        id: "EC-006",
        title: "More Information Requested",
        subject: "Additional Information Needed — Grievance {{id}}",
        recipients: ["Submitter"],
        channel: ["SMS", "Email"],
        trigger: "Officer sets More Info Needed",
        active: true,
        template: "Dear {{name}},\n\nThe officer handling your grievance ({{id}}) requires additional information to proceed.\n\nInformation requested: {{infoRequest}}\n\nPlease respond by: {{responseDeadline}}\n\nYou can reply via the OAN portal or call our helpline. Delays in responding may pause your SLA clock.\n\nOAN Ethiopia Grievance Portal",
        lastEdited: "2026-04-10T14:00:00Z",
    },
    {
        id: "EC-007",
        title: "Submitter Responds to Info Request",
        subject: "Submitter Response Received — Grievance {{id}}",
        recipients: ["L1 Officer"],
        channel: ["Email"],
        trigger: "Submitter provides requested info",
        active: true,
        template: "Dear {{officerName}},\n\nThe submitter has responded to your information request for grievance {{id}}.\n\nResponse: {{submitterResponse}}\n\nPlease review and continue processing.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-15T09:00:00Z",
    },
    {
        id: "EC-008",
        title: "Structured Response Sent to Submitter",
        subject: "Department Response on Grievance {{id}}",
        recipients: ["Submitter"],
        channel: ["SMS", "Email"],
        trigger: "Officer submits structured response",
        active: true,
        template: "Dear {{name}},\n\nThe department has submitted a response to your grievance ({{id}}).\n\nAction taken: {{actionTaken}}\nResolution summary: {{resolutionSummary}}\nProposed closure date: {{closeDate}}\n\nYou have 7 days to confirm resolution or reopen the grievance. Log in to the OAN Portal to respond.\n\nOAN Ethiopia Grievance Portal",
        lastEdited: "2026-04-15T09:30:00Z",
    },
    {
        id: "EC-009",
        title: "Confirmation Window Open",
        subject: "Action Required — Confirm Resolution of Grievance {{id}}",
        recipients: ["Submitter"],
        channel: ["SMS"],
        trigger: "Response submitted",
        active: true,
        template: "OAN: Grievance {{id}} response received. Reply CONFIRM to close or REOPEN with reason. You have 7 days. Portal: oan.gov.et/grievances/{{id}}",
        lastEdited: "2026-04-15T09:30:00Z",
    },
    {
        id: "EC-010",
        title: "Grievance Confirmed / Resolved",
        subject: "Grievance {{id}} Resolved — Thank You",
        recipients: ["Submitter"],
        channel: ["SMS", "Email"],
        trigger: "Submitter confirms satisfaction",
        active: true,
        template: "Dear {{name}},\n\nYour grievance ({{id}}) has been marked as Resolved.\n\nWe would appreciate your feedback. Please rate your experience (1–5) at: oan.gov.et/rate/{{id}}\n\nThank you for using the OAN Ethiopia Grievance Portal.",
        lastEdited: "2026-03-28T11:00:00Z",
    },
    {
        id: "EC-011",
        title: "Grievance Reopened",
        subject: "[OAN] Grievance {{id}} Reopened by Submitter",
        recipients: ["L1 Officer"],
        channel: ["Email"],
        trigger: "Submitter reopens grievance",
        active: true,
        template: "Dear {{officerName}},\n\nGrievance {{id}} has been reopened by the submitter.\n\nReopen reason: {{reopenReason}}\n\nPlease review the outstanding concerns and resubmit a structured response.\n\nOAN Ethiopia System",
        lastEdited: "2026-03-28T11:00:00Z",
    },
    {
        id: "EC-012",
        title: "Auto-closed (No Response)",
        subject: "Grievance {{id}} Auto-Closed — No Objection Received",
        recipients: ["Submitter"],
        channel: ["SMS", "Email"],
        trigger: "Confirmation window expires",
        active: true,
        template: "Dear {{name}},\n\nYour grievance ({{id}}) has been automatically closed as no response was received within the 7-day confirmation window.\n\nIf you are not satisfied, you may raise a new grievance referencing ticket {{id}}.\n\nOAN Ethiopia Grievance Portal",
        lastEdited: "2026-04-02T08:00:00Z",
    },
    {
        id: "EC-013",
        title: "SLA Reminder — 50%",
        subject: "[Reminder] SLA at 50% — Grievance {{id}}",
        recipients: ["L1 Officer"],
        channel: ["Email"],
        trigger: "Scheduled job at 50% SLA elapsed",
        active: true,
        template: "Dear {{officerName}},\n\nThis is a reminder that grievance {{id}} is at 50% of its SLA deadline.\n\nSubmitter: {{submitterName}}\nCategory: {{category}}\nSLA Deadline: {{slaDeadline}} ({{daysRemaining}} days remaining)\n\nPlease take action promptly.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-15T09:30:00Z",
    },
    {
        id: "EC-014",
        title: "SLA Reminder — 80%",
        subject: "[URGENT] SLA at 80% — Grievance {{id}}",
        recipients: ["L1 Officer"],
        channel: ["Email"],
        trigger: "Scheduled job at 80% SLA elapsed",
        active: true,
        template: "Dear {{officerName}},\n\nURGENT: Grievance {{id}} has consumed 80% of its SLA. Immediate action is required.\n\nSLA Deadline: {{slaDeadline}} ({{daysRemaining}} days remaining)\n\nOAN Ethiopia System",
        lastEdited: "2026-04-15T09:30:00Z",
    },
    {
        id: "EC-015",
        title: "SLA At-Risk Report (Nodal Officer)",
        subject: "SLA At-Risk Digest — {{count}} Tickets Near Deadline",
        recipients: ["Nodal Officer"],
        channel: ["Email"],
        trigger: "Scheduled job at 80% SLA elapsed",
        active: true,
        template: "Dear {{nodalOfficerName}},\n\nThe following grievances are approaching their SLA deadline and have reached 80% elapsed time:\n\n{{ticketList}}\n\nPlease review and intervene where necessary.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-15T09:30:00Z",
    },
    {
        id: "EC-016",
        title: "SLA Breached — L1 Escalation",
        subject: "[ESCALATED] SLA Breached — Grievance {{id}}",
        recipients: ["Dept Head", "Nodal Officer"],
        channel: ["Email"],
        trigger: "SLA deadline passed",
        active: true,
        template: "ESCALATION NOTICE\n\nGrievance {{id}} has exceeded its SLA deadline of {{slaDays}} days.\n\nDays overdue: {{daysOverdue}}\nSubmitter: {{submitterName}}\nCategory: {{category}} — {{grievanceType}}\nAssigned officer: {{officerName}}\n\nImmediate action is required. This escalation has been logged in the audit trail.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-10T14:00:00Z",
    },
    {
        id: "EC-017",
        title: "SLA Breached — L2 Escalation",
        subject: "[L2 ESCALATION] 2× SLA Breached — Grievance {{id}}",
        recipients: ["L2 Officer"],
        channel: ["Email"],
        trigger: "2× SLA deadline passed",
        active: true,
        template: "SECOND-LEVEL ESCALATION\n\nGrievance {{id}} has exceeded twice its SLA deadline.\n\nDays overdue: {{daysOverdue}}\nCategory: {{category}}\nFull history available on OAN Portal.\n\nAll prior stakeholders remain notified. Your intervention is required.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-10T14:00:00Z",
    },
    {
        id: "EC-018",
        title: "Manual Escalation by Submitter",
        subject: "[MANUAL ESCALATION] Grievance {{id}} Escalated by Submitter",
        recipients: ["Dept Head", "Nodal Officer"],
        channel: ["Email"],
        trigger: "Submitter triggers escalation via portal",
        active: true,
        template: "MANUAL ESCALATION\n\nSubmitter {{submitterName}} has manually escalated grievance {{id}} after SLA elapsed.\n\nReason provided: {{escalationReason}}\nDays overdue: {{daysOverdue}}\n\nThis triggers the same notifications as an SLA breach escalation.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-10T14:00:00Z",
    },
    {
        id: "EC-019",
        title: "Reassignment Requested",
        subject: "[OAN] Reassignment Requested — Grievance {{id}}",
        recipients: ["Nodal Officer"],
        channel: ["Email"],
        trigger: "Officer requests reassignment",
        active: true,
        template: "Dear {{nodalOfficerName}},\n\nOfficer {{officerName}} ({{dept}}) has requested reassignment of grievance {{id}}.\n\nReason: {{reassignReason}}\n\nPlease review and assign to the appropriate department.\n\nOAN Ethiopia System",
        lastEdited: "2026-04-05T10:30:00Z",
    },


];

export const MOCK_ESCALATION_NOTIFICATIONS: NotificationConfig[] = [];
